//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleApartado
    {
        public int IdDetalleApartado { get; set; }
        public int IdApartado { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Sku { get; set; }
        public string NombreProducto { get; set; }
        public double Precio { get; set; }
        public double Total { get; set; }
    
        public virtual Apartado Apartado { get; set; }
    }
}
