//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdDetalle_Factura { get; set; }
        public int IdFactura { get; set; }
        public int Cantidad { get; set; }
        public string Sku { get; set; }
        public string NombreProducto { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual vInventario vInventario  { get; set; }

        #region ViewModels
        public partial class DetalleFacturaViewModel
        {
            public string Sku { get; set; }
            public string ProductoNombre { get; set; }
            public int Cantidad { get; set; }
            public decimal Precio { get; set; }
            public bool Retirar { get; set; }
            public decimal Monto()
            {
                return Cantidad * Precio;
            }
        }
        #endregion
    }
}
