//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosOrganizacion
    {
        public int IdGastosOrganizacion { get; set; }
        public int IdGasto { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdSucursal { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime CreadoUTC { get; set; }
        public System.DateTime ModificadoUTC { get; set; }
    
        public virtual Gasto Gasto { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
