//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.PagoRecibo = new HashSet<PagoRecibo>();
        }
    
        public int IdRecibo { get; set; }
        public int IdCliente { get; set; }
        public int IdApartado { get; set; }
        public double Cuota { get; set; }
        public double IVA { get; set; }
        public bool Anulado { get; set; }
        public double Tasa { get; set; }
    
        public virtual Apartado Apartado { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRecibo> PagoRecibo { get; set; }
    }
}
